# config.py
import os
STORMGLASS_API_KEY = os.environ['STORMGLASS_API_KEY']
EMAIL_ADDRESS = os.environ['EMAIL_ADDRESS']
EMAIL_PASSWORD = os.environ['EMAIL_PASSWORD']
ADDITIONAL_EMAIL = "Micheal@desiun.ie"
TWILIO_ACCOUNT_SID = os.environ['TWILIO_ACCOUNT_SID']
TWILIO_AUTH_TOKEN = os.environ['TWILIO_AUTH_TOKEN']
TWILIO_FROM_NUMBER = os.environ['TWILIO_FROM_NUMBER']
WHATSAPP_TO_NUMBER = os.environ['WHATSAPP_TO_NUMBER']