[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "astral>=3.2",
    "requests>=2.32.3",
    "twilio>=8.5.0",
]
